### ISSUE TITLE
Initial build appears to fail 

### ISSUE THREAD

**Issue by JesseCake** [autc04/Retro68#106]
My initial build, built with --no-ppc option appears to fail ending with:

find: ‘../../universal/libppc’: No such file or directory

Unless this is just the outcome of not building the ppc side of the toolchain? Should I get more feedback or is this just the end of the output?

Edit: I've found it's specifically if you try to build only the 68k side of things, as some part just after the converting of the apple universal libraries still expects to work on the ppc files which of course aren't being built.

Separately, it appears building the PPC toolchain also fails, with linking the console library. Should I log this as a separate issue?

My build environment is Ubuntu Linux 18.04 with all of the libraries installed as per the instructions readme.

**Comment by autc04** [comment]
Thanks for the report, I'll have a look tomorrow.

**Comment by autc04** [comment]
Both issues should be fixed now, thanks again for the report!
