### ISSUE TITLE
generated disk image size

### ISSUE THREAD

**Issue by cy384** [autc04/Retro68#109]
it seems like the generated disk images are 800k, and if your binary is larger than will fit, it gets silently truncated (until you try to run it, then you get a Mac OS -39 error).

is there a way to adjust this? (or perhaps there needs to be some size detection added somewhere?)

thanks!

**Comment by autc04** [comment]
https://github.com/autc04/Retro68/blob/3992bf904a93d66a1feefa6c89af221a3430457e/ResourceFiles/ResourceFile.cc#L524

Looks like that's a bug. There is size detection, but it seems to use only the size of the resource fork (which is fine for 68K apps, but bad for PPC apps).

**Comment by cy384** [comment]
adding data.size() to that line seems to work fine

separately, it seems like the build is broken right now, it errors out when trying to compile one of the samples because it can't find the retroconsole lib.  I can open another issue for that if you'd like.

**Comment by autc04** [comment]
> it errors out when trying to compile one of the samples because it can't find the retroconsole lib.
@cy384 could you open a ticket for that with some details? The automated builds on Azure went through without trouble, so that's new to me.

**Comment by cy384** [comment]
I just did a fresh clone and build with no problems, so I guess it was some transient issue on my machine

thanks!
