### ISSUE TITLE
Cygwin libhfs Compile Error

### ISSUE THREAD

**Issue by JaredWhiteOne** [autc04/Retro68#112]
I am attempting to build Retro68 on the latest master branch in Cygwin and am getting the following error when it attempts to build libhfs:

cd libhfs && make
make[1]: Entering directory '/cygdrive/f/Projects/retro68-build/hfsutils/libhfs'
rm -f os.c
ln -s os/unix.c os.c
gcc -g -O2 -I. -DHAVE_CONFIG_H   -c -o os.o os.c
gcc: error: os.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
make[1]: *** [<builtin>: os.o] Error 1
make[1]: Leaving directory '/cygdrive/f/Projects/retro68-build/hfsutils/libhfs'
make: *** [Makefile:219: libhfs/libhfs.a] Error 2

**Comment by autc04** [comment]
Strange. Does the `ln -s` command not work properly on cygwin any more?
Does `/cygdrive/f/Projects/retro68-build/hfsutils/libhfs/os.c` exist?

I don't have  a cygwin installation to test this myself.

Potential workarounds:
(a) Lines 119-121 of `hfsutils/libhfs/Makefile.in` read:
```
os.c: os/$(OS).c
	rm -f $@
	$(SOFTLINK) os/$(OS).c $@
```
Change the last line (121) to
```
	cp os/$(OS).c $@
```

(b) Give up and use Linux inside WSL instead.

**Comment by JaredWhiteOne** [comment]
@autc04 Thanks for the quick reply! I'm going in manually and trying the command after some discovery and it looks like this will have to be changed to a copy for cygwin as symbolically linking via ln -s doesn't seem to function. I'm not 100% sure your reasoning for a symbolic link but since you suggested it I suspect it's a valid idea.

**Comment by autc04** [comment]
Anyway, the symbolic link here dates back to the year 1998 (hfsutils is not my own code but an old third-party project), and I am sure we can do without. It might be cleaner to just move the file to its final place by hand and remove the commands from the Makefile.

But I'm still a bit confused, as creating symbolic links using `ln -s` used to work under cygwin the last time I used it.
