### ISSUE TITLE
High level questions: threading and networing

### ISSUE THREAD

**Issue by dymczykm** [autc04/Retro68#114]
Hello, 
I've recently started looking into Retro68 (this effort really is fantastic) and wanted to ask about two topics.

**1) Threading**
I've done a couple of simple apps for fun and stumbled upon a problem with `pthread`. I can successfully include the header `pthread.h`, but I'm missing it when linking, e.g.:
```
test.cpp:(.text+0x9a2): undefined reference to `pthread_mutex_unlock'
```
Normally, on a *nix system I would try to link against `pthread` which also seems to fail:
```
.../retro68/Retro68-build/toolchain/lib/gcc/m68k-apple-macos/9.1.0/../../../../m68k-apple-macos/bin/ld.real: cannot find -lpthread
```
Is this expected or is it my mistake somewhere?

**2) Networking**
Do I get it right that the right thing to do is to talk directly to `MacTcp` and there's no Unix-like socket interface present?

I'm sorry if I missed a doc/resource that would answer those questions, I've tried to look for it but haven't found any.

Thanks a lot for your help!

Kind regards (and a happy New Year!),
Marcin

**Comment by autc04** [comment]
Yes, unfortunately expected in both cases, you have to go to the native APIs for now (or, if you have excessive amounts of time on your hands, extend Retro68's standard library).

For threads, you also need to be aware of classic MacOS's limitations in this regard. Basically, you will have to choose between the Thread Manager (System 7.5. or later, IIRC), where you need to explicitly 'yield' between the cooperative threads it implements, and the later Multiprocessing Services, where not even `malloc` is allowed to be used from any but the main thread.


There used to be an open-source library for MacOS 7-9 that implemented both unix-style network and thread APIs based on Apple's stuff: https://sourceforge.net/projects/gusi/ 

It would be a major project to integrate it with the C library that is currently used (`newlib`).

**Comment by dymczykm** [comment]
Thanks a lot for the answer - particularly the threading limitations sounds a bit scary, let's see how it goes.

I indeed started looking into some existing source code that was using GUSI (e.g. [MacSSH](https://github.com/macssh) or MacLynx) and will try to evaluate how much porting effort is necessary.

I'll close this issue and will come back should any more specific questions arise. Thanks!
