### ISSUE TITLE
printf, character constants and error 3

### ISSUE THREAD

**Issue by dymczykm** [autc04/Retro68#115]
I decided to do a project with Retro68 and try to port links (the web browser) to Mac OS Classic.

As @autc04 suggested, I've ported GUSI to Retro68 (not tested yet, but it builds and generally was not too bad - I will definitely put it up on GitHub once loose ends are fixed). Now, I'm also successfully building links against GUSI and Retro68 and using the Retro Console (same as the `HelloWorld` sample).

While debugging the code I've noticed that I'm experiencing some hard to explain behaviour when printing messages. I'm suspecting I'm missing some MacOS knowledge about limitations. For example, I have a simple function where I replaced all the logic by a simple a simple `printf`:
```
void init_home(void) {
  printf("pong\n");
}
```
The function `init_home` is called from the `initialize_all_subsystems` function:
```
static void initialize_all_subsystems(void) {
    init_charset();
    init_trans();
    set_sigcld();
    init_home();  // Comment out to avoid error 3.
    init_dns();
    init_session_cache();
    // FIXME-MACOS This is still causing an error 3.
    //init_cache();
    //init_blocks();
    memset(&dd_opt, 0, sizeof dd_opt);
}
```
After building the app and loading it as `.dsk` to Basilisk II running System 7.5 I'm getting an `Error 3` immediately after starting the app:
![Selection_078](https://user-images.githubusercontent.com/6044558/103479565-df4e8980-4dce-11eb-9470-426f56127898.png)

When removing either the `printf` statement or commenting out `init_home();` the issue disappears. I've noticed this behavior in certain other places, where adding a simple printf with a constant caused the app to trigger an error at startup. On the other hand, in some other places `printf` works perfectly fine.

Now, the questions:
- Is this looking like some known limitation of Retro68, console or Mac OS?
- I'm suspecting this might be related to Resources, should the `printf` constants be defined in `.r` files?
- Is this maybe depending on the total executable size? It seems I can expand the `HelloWorld` sample to as much text as I want without triggering this issue.

Thanks a lot for your help!

**Comment by autc04** [comment]
Sounds cool!

First, don't worry about character constants. The advice to put them in resources was always just because that makes it more convenient to translate an application to different languages, never because of any limitation of MacOS.

My first ideas for things to check for:
* Your application should have a proper SIZE resource, which determines how much memory gets allocated to it. The Retro68 CMake scripts create one by default, but the amount of memory allocated there might be too small.
* I think the GUSI library duplicates some functions defined by the C standard library. Are you sure you're getting the right version of all functions you are using?
* Who is initializing the MacOS Toolbox? The RetroConsole library does that automatically, and if GUSI does it as well, that might cause trouble.

Looking forward to that GitHub repo :-)

**Comment by dymczykm** [comment]
@autc04 Thanks a lot for your answer, I actually kept on looking into the problem and it seems your advice might be spot on.

1) I'm pretty sure this is at least a part of the problem - I'm clearly getting weird situations where I can compile in different code parts, but never all of them at once. So missing a SIZE resource sounds very very plausible. I'll follow the info in the Macintosh Toolbox Essentials document and also the example of [MacHTTP](https://github.com/antscode/MacHTTP/blob/master/size.r).
2) Yes, that was actually the biggest challenge, I've tried to use `newlib` code whenever possible. Some errors are possible, but here it seems it's just too random to be it.
3) Good question - I will look into that, I haven't really checked that.

Will keep you posted, I'm pretty sure more questions will pop up :)

**Comment by autc04** [comment]
Also look at the Dialog Sample for how to add your own SIZE resource. For testing, you could also just use the Mac Finder's Get Info Dialog to increase memory allocation for the application after the fact.

**Comment by dymczykm** [comment]
@autc04 just wanted to say that adding a SIZE resource helped and now the app behaves in a predictable fashion and the initialization functions complete without any issue. Thanks a lot!

I will still look into your suggestions from points 2) and 3) to confirm everything's right over there.

**Comment by autc04** [comment]
Any updates?

**Comment by dymczykm** [comment]
@autc04 thanks for asking and sorry for no further report!

I can confirm that the SIZE resource fixed the issues. Regarding other points:

2) It's still not 100% clear but so far the initialization is working fine and I'm getting now a fully initialized browser. The trouble starts once I'm trying to use MacTCP (I'm getting a Links error saying "No more processes"). My next immediate steps will be:
    * Fix the local filesystem handling (paths with `:`...).
    * Open a local html file and see if HTML parsing/drawing works.
    * Then, I'll proceed with debugging the networking (and will probably ask more questions :)).

3) This is fine - RetroConsole initializes the Toolbox and GUSI expects it to be initialized. So that's totally fine.

Feel free to close this issue.

**Comment by autc04** [comment]
Cool :-)

BTW, I'd love to see your work in progress, especially the GUSI-related part. "Integrating GUSI" has been on my "TODO but not now"-list for ages...
