### ISSUE TITLE
Not all samples running in Macintosh 128K

### ISSUE THREAD

**Issue by muimota** [autc04/Retro68#118]
In an emulated Mac 128K using [vMac 128k](https://www.gryphel.com/c/minivmac/dnld_128.html) and a 32Kb ROM, Raytrace and Console examples crash with an error code **ID=12** which [error code](http://www.macwizard.com/errors.html) description is **"Unimplemented Core Routine"** 
![image](https://user-images.githubusercontent.com/6080740/104127836-a9784a80-5364-11eb-9ce3-3eacb5544f00.png)

Is there a way to compile Retro68 examples for the Macintosh 128K?
I am writing some code that uses quickdraw and I plan to run it in a Macintosh 128K in the future. 

All the samples work perfectly when using the standard [vMac](https://www.gryphel.com/c/minivmac/dnld_std.html)

**Comment by autc04** [comment]
Ok, I'll have to double-check whether any of these examples use routines that didn't exist in the first versions.
Some of the examples will likely need more than 128K of RAM, so those will never work.

**Comment by muimota** [comment]
I've been editing de cmake files and after replacing *--mac-strip-macsbug* with *--mac-single* works on Mac128K
**HelloWorld**
```
set_target_properties(HelloWorld PROPERTIES COMPILE_OPTIONS -ffunction-sections)
if(CMAKE_SYSTEM_NAME MATCHES Retro68)
    set_target_properties(HelloWorld PROPERTIES LINK_FLAGS "-Wl,-gc-sections -Wl,--mac-single")

else()
    set_target_properties(HelloWorld PROPERTIES LINK_FLAGS "-Wl,-gc-sections")
endif()
```

**Raytracer2**   
It started but immediately stopped with error code 15, I guess it ran out of memory

**Comment by autc04** [comment]
Found it. The `Get1Resource` call wasn't actually available in the first system versions.

Raytracer now works as well, but Raytracer2 runs out of memory while trying to load its code.
I had no success with HelloWorld either, but of course I have the MacsBug debugger installed in my 128K minivmac, which takes away another 13K of precious RAM.

Raytracer2 and the Console library are both written in C++, which means they include some 50-65K of extra library code. That's already worth it on a Mac Plus, but deadly on a Mac 128K...

**Comment by zulc22** [comment]
shouldn't this issue be closed?

**Comment by autc04** [comment]
Probably :-)
