### ISSUE TITLE
Can't compile Retro68 on WSL

### ISSUE THREAD

**Issue by Rorybabory2** [autc04/Retro68#121]
I'm running an ubuntu terminal using WSL, and when I try to compile Retro68, I get an error that says:

ruby: No such file or directory -- make-multiverse.rb (LoadError)

After that when I tried to compile a sample program with cmake I get two errors, that say:

configure_file Problem configuring file

and

Unknown CMake command "add_application"

**Comment by zulc22** [comment]
`ruby: No such file or directory` implies you haven't installed Ruby, which is in the apt command in README.MD.

**Comment by Rorybabory2** [comment]
It says ruby is at the newest version. I think it may be saying that it can't find make-multiverse.rb

**Comment by zulc22** [comment]
can you run '`ruby`' at your command line?

**Comment by Rorybabory2** [comment]
yes

**Comment by autc04** [comment]
Did you download the git submodules? That is, have you used the `--recursive` option when cloning or used the command `git submodule update --init` afterwards?

**Comment by autc04** [comment]
Closing because there was no response.

**Comment by frogsquire** [comment]
Hey @autc04 @Rorybabory2 , I also had the `Unknown CMake command "add_application"` error on WSL, and I solved it by pulling the latest cmake for Ubuntu 18.04 LTS following the instructions at https://askubuntu.com/questions/355565/how-do-i-install-the-latest-version-of-cmake-from-the-command-line. After doing this, Retro68 builds great.
