### ISSUE TITLE
Problems with compiling

### ISSUE THREAD

**Issue by marcusnilsen** [autc04/Retro68#14]
Hi, I have problems building Retro68. I'm running OS X 10.10.1, Xcode 6.1.1.
The first time I tried building the toolchain I got "fatal error: 'boost/filesystem.hpp' file not found", which I fixed by installing boost with brew. After trying 'build-toolchain.sh' again I got this error after a while:

.....
/usr/bin/install -c -m 755 ld-elf2flt /retro68-build/toolchain/m68k-unknown-elf/bin/ld
/usr/bin/install -c -m 644 elf2flt.ld /retro68-build/toolchain/m68k-unknown-elf/lib/elf2flt.ld
creating cache ./config.cache
checking whether make sets ${MAKE}... yes
checking for gcc... gcc
checking whether the C compiler (gcc  ) works... yes
checking whether the C compiler (gcc  ) is a cross-compiler... no
checking whether we are using GNU C... yes
checking whether gcc accepts -g... yes
checking for a BSD compatible install... /usr/bin/install -c
checking for ranlib... ranlib
checking how to run the C preprocessor... gcc -E
checking whether gcc needs -traditional... no
checking for ANSI C header files... yes
checking for unistd.h... yes
checking for fcntl.h... yes
checking for termios.h... yes
checking for sys/ioctl.h... yes
checking for uid_t in sys/types.h... yes
checking for size_t... yes
checking for working const... yes
checking for strdup... yes
checking for strerror... yes
checking for strstr... yes
checking for strtol... yes
checking for setreuid... yes
checking for sys_errlist... yes
updating cache ./config.cache
creating ./config.status
creating hfsck/Makefile
creating linux/Makefile
creating Makefile
creating config.h
configuring in libhfs
running /bin/sh ./configure  --prefix=/retro68-build/toolchain/ --enable-devlibs --cache-file=.././config.cache --srcdir=.
loading cache .././config.cache
checking whether make sets ${MAKE}... (cached) yes
checking for gcc... (cached) gcc
checking whether the C compiler (gcc  ) works... yes
checking whether the C compiler (gcc  ) is a cross-compiler... no
checking whether we are using GNU C... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for a BSD compatible install... (cached) /usr/bin/install -c
checking for ranlib... (cached) ranlib
checking whether ln -s works... yes
checking how to run the C preprocessor... (cached) gcc -E
checking whether gcc needs -traditional... (cached) no
checking for ANSI C header files... (cached) yes
checking for unistd.h... (cached) yes
checking for fcntl.h... (cached) yes
checking for size_t... (cached) yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking for working const... (cached) yes
checking for 8-bit clean memcmp... yes
checking for mktime... yes
updating cache .././config.cache
creating ./config.status
creating Makefile
creating config.h
configuring in librsrc
running /bin/sh ./configure  --prefix=/retro68-build/toolchain/ --enable-devlibs --cache-file=.././config.cache --srcdir=.
loading cache .././config.cache
checking whether make sets ${MAKE}... (cached) yes
checking for gcc... (cached) gcc
checking whether the C compiler (gcc  ) works... yes
checking whether the C compiler (gcc  ) is a cross-compiler... no
checking whether we are using GNU C... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for a BSD compatible install... (cached) /usr/bin/install -c
checking for ranlib... (cached) ranlib
checking how to run the C preprocessor... (cached) gcc -E
checking whether gcc needs -traditional... (cached) no
checking for ANSI C header files... (cached) yes
checking for unistd.h... (cached) yes
checking for fcntl.h... (cached) yes
checking for size_t... (cached) yes
checking whether struct tm is in sys/time.h or time.h... (cached) time.h
checking for working const... (cached) yes
checking for mktime... (cached) yes
creating ./config.status
creating Makefile
creating config.h
cd libhfs && /Applications/Xcode.app/Contents/Developer/usr/bin/make
gcc -g -O2  -DHAVE_CONFIG_H   -c -o os.o os.c
os.c:86:11: warning: cast to 'void *' from smaller integer type 'int' [-Wint-to-void-pointer-cast]
  *priv = (void *) fd;
          ^
1 warning generated.
gcc -g -O2  -DHAVE_CONFIG_H   -c -o data.o data.c
gcc -g -O2  -DHAVE_CONFIG_H   -c -o block.o block.c
gcc -g -O2  -DHAVE_CONFIG_H   -c -o low.o low.c
gcc -g -O2  -DHAVE_CONFIG_H   -c -o medium.o medium.c
gcc -g -O2  -DHAVE_CONFIG_H   -c -o file.o file.c
gcc -g -O2  -DHAVE_CONFIG_H   -c -o btree.o btree.c
btree.c:444:32: warning: passing 'int *' to parameter of type 'unsigned int *' converts between pointers to integer types with different sign [-Wpointer-sign]
        result = n_insert(np, record, reclen);
                                      ^~~~~~
./node.h:32:44: note: passing argument to parameter here
int n_insert(node *, byte *, unsigned int *);
                                           ^
btree.c:449:37: warning: passing 'int *' to parameter of type 'unsigned int *' converts between pointers to integer types with different sign [-Wpointer-sign]
      result = n_insert(np, record, reclen);
                                    ^~~~~~
./node.h:32:44: note: passing argument to parameter here
int n_insert(node *, byte *, unsigned int *);
                                           ^
btree.c:493:30: warning: passing 'unsigned int *' to parameter of type 'int *' converts between pointers to integer types with different sign [-Wpointer-sign]
  if (insertx(&root, newrec, &reclen) == -1)
                             ^~~~~~~
btree.c:412:42: note: passing argument to parameter 'reclen' here
int insertx(node *np, byte *record, int *reclen)
                                         ^
3 warnings generated.
gcc -g -O2  -DHAVE_CONFIG_H   -c -o node.o node.c
gcc -g -O2  -DHAVE_CONFIG_H   -c -o record.o record.c
gcc -g -O2  -DHAVE_CONFIG_H   -c -o volume.o volume.c
gcc -g -O2  -DHAVE_CONFIG_H   -c -o hfs.o hfs.c
hfs.c:672:45: warning: passing 'unsigned long *' to parameter of type 'long *' converts between pointers to integer types with different sign [-Wpointer-sign]
  found = v_resolve(&vol, path, &file->cat, &parid, name, 0);
                                            ^~~~~~
./volume.h:57:60: note: passing argument to parameter here
int v_resolve(hfsvol **, const char *, CatDataRec *, long *, char *, node *);
                                                           ^
hfs.c:743:41: warning: passing 'unsigned long *' to parameter of type 'long *' converts between pointers to integer types with different sign [-Wpointer-sign]
  if (v_resolve(&vol, path, &file->cat, &file->parid, file->name, 0) <= 0)
                                        ^~~~~~~~~~~~
./volume.h:57:60: note: passing argument to parameter here
int v_resolve(hfsvol **, const char *, CatDataRec *, long *, char *, node *);
                                                           ^
hfs.c:1037:36: warning: passing 'unsigned long *' to parameter of type 'long *' converts between pointers to integer types with different sign [-Wpointer-sign]
      v_resolve(&vol, path, &data, &parid, name, 0) <= 0)
                                   ^~~~~~
./volume.h:57:60: note: passing argument to parameter here
int v_resolve(hfsvol **, const char *, CatDataRec *, long *, char *, node *);
                                                           ^
hfs.c:1116:40: warning: passing 'unsigned long *' to parameter of type 'long *' converts between pointers to integer types with different sign [-Wpointer-sign]
  found = v_resolve(&vol, path, &data, &parid, name, 0);
                                       ^~~~~~
./volume.h:57:60: note: passing argument to parameter here
int v_resolve(hfsvol **, const char *, CatDataRec *, long *, char *, node *);
                                                           ^
hfs.c:1148:36: warning: passing 'unsigned long *' to parameter of type 'long *' converts between pointers to integer types with different sign [-Wpointer-sign]
      v_resolve(&vol, path, &data, &parid, name, 0) <= 0)
                                   ^~~~~~
./volume.h:57:60: note: passing argument to parameter here
int v_resolve(hfsvol **, const char *, CatDataRec *, long *, char *, node *);
                                                           ^
hfs.c:1198:40: warning: passing 'unsigned long *' to parameter of type 'long *' converts between pointers to integer types with different sign [-Wpointer-sign]
      v_resolve(&vol, path, &file.cat, &file.parid, file.name, 0) <= 0)
                                       ^~~~~~~~~~~
./volume.h:57:60: note: passing argument to parameter here
int v_resolve(hfsvol **, const char *, CatDataRec *, long *, char *, node *);
                                                           ^
hfs.c:1273:38: warning: passing 'unsigned long *' to parameter of type 'long *' converts between pointers to integer types with different sign [-Wpointer-sign]
      v_resolve(&vol, srcpath, &src, &srcid, srcname, 0) <= 0)
                                     ^~~~~~
./volume.h:57:60: note: passing argument to parameter here
int v_resolve(hfsvol **, const char *, CatDataRec *, long *, char *, node *);
                                                           ^
hfs.c:1279:42: warning: passing 'unsigned long *' to parameter of type 'long *' converts between pointers to integer types with different sign [-Wpointer-sign]
  found = v_resolve(&vol, dstpath, &dst, &dstid, dstname, 0);
                                         ^~~~~~
./volume.h:57:60: note: passing argument to parameter here
int v_resolve(hfsvol **, const char *, CatDataRec *, long *, char *, node *);
                                                           ^
8 warnings generated.
gcc -g -O2  -DHAVE_CONFIG_H   -c -o version.o version.c
ar rc libhfs.a os.o data.o block.o low.o medium.o file.o btree.o node.o record.o volume.o hfs.o version.o
ranlib libhfs.a
gcc -g -O2 -Ilibhfs   -DHAVE_CONFIG_H   -c -o hfsutil.o hfsutil.c
hfsutil.c:292:28: warning: passing 'long *' to parameter of type 'unsigned long *' converts between pointers to integer types with different sign [-Wpointer-sign]
      if (hfs_dirinfo(vol, &cwd, name) == -1)
                           ^~~~
libhfs/hfs.h:148:42: note: passing argument to parameter here
int hfs_dirinfo(hfsvol *, unsigned long *, char *);
                                         ^
1 warning generated.
gcc -g -O2 -Ilibhfs   -DHAVE_CONFIG_H   -c -o hcwd.o hcwd.c
gcc -g -O2 -Ilibhfs   -DHAVE_CONFIG_H   -c -o hattrib.o hattrib.c
gcc -g -O2 -Ilibhfs   -DHAVE_CONFIG_H   -c -o hcd.o hcd.c
gcc -g -O2 -Ilibhfs   -DHAVE_CONFIG_H   -c -o hcopy.o hcopy.c
gcc -g -O2 -Ilibhfs   -DHAVE_CONFIG_H   -c -o hdel.o hdel.c
gcc -g -O2 -Ilibhfs   -DHAVE_CONFIG_H   -c -o hformat.o hformat.c
gcc -g -O2 -Ilibhfs   -DHAVE_CONFIG_H   -c -o hls.o hls.c
gcc -g -O2 -Ilibhfs   -DHAVE_CONFIG_H   -c -o hmkdir.o hmkdir.c
gcc -g -O2 -Ilibhfs   -DHAVE_CONFIG_H   -c -o hmount.o hmount.c
gcc -g -O2 -Ilibhfs   -DHAVE_CONFIG_H   -c -o hpwd.o hpwd.c
hpwd.c:55:7: warning: implicitly declaring library function 'strcmp' with type 'int (const char *, const char *)'
  if (strcmp(ent->cwd, ":") == 0)
      ^
hpwd.c:55:7: note: please include the header <string.h> or explicitly provide a declaration for 'strcmp'
1 warning generated.
gcc -g -O2 -Ilibhfs   -DHAVE_CONFIG_H   -c -o hrename.o hrename.c
gcc -g -O2 -Ilibhfs   -DHAVE_CONFIG_H   -c -o hrmdir.o hrmdir.c
gcc -g -O2 -Ilibhfs   -DHAVE_CONFIG_H   -c -o humount.o humount.c
gcc -g -O2 -Ilibhfs   -DHAVE_CONFIG_H   -c -o hvol.o hvol.c
gcc -g -O2 -Ilibhfs   -DHAVE_CONFIG_H   -c -o crc.o crc.c
gcc -g -O2 -Ilibhfs   -DHAVE_CONFIG_H   -c -o binhex.o binhex.c
gcc -g -O2 -Ilibhfs   -DHAVE_CONFIG_H   -c -o copyin.o copyin.c
gcc -g -O2 -Ilibhfs   -DHAVE_CONFIG_H   -c -o copyout.o copyout.c
gcc -g -O2 -Ilibhfs   -DHAVE_CONFIG_H   -c -o charset.o charset.c
gcc -g -O2 -Ilibhfs   -DHAVE_CONFIG_H   -c -o darray.o darray.c
gcc -g -O2 -Ilibhfs   -DHAVE_CONFIG_H   -c -o dlist.o dlist.c
gcc -g -O2 -Ilibhfs   -DHAVE_CONFIG_H   -c -o dstring.o dstring.c
gcc -g -O2 -Ilibhfs   -DHAVE_CONFIG_H   -c -o glob.o glob.c
gcc -g -O2 -Ilibhfs   -DHAVE_CONFIG_H   -c -o suid.o suid.c
gcc -g -O2 -Ilibhfs   -DHAVE_CONFIG_H   -c -o version.o version.c
gcc -Llibhfs hfsutil.o hcwd.o   \
		hattrib.o hcd.o hcopy.o hdel.o hformat.o hls.o hmkdir.o hmount.o hpwd.o hrename.o hrmdir.o humount.o hvol.o crc.o binhex.o copyin.o copyout.o charset.o darray.o dlist.o dstring.o glob.o suid.o version.o  \
		-lhfs   -o hfsutil
ln -f hfsutil hattrib
ln -f hfsutil hcd
ln -f hfsutil hcopy
ln -f hfsutil hdel
ln -f hfsutil hdir
ln -f hfsutil hformat
ln -f hfsutil hls
ln -f hfsutil hmkdir
ln -f hfsutil hmount
ln -f hfsutil hpwd
ln -f hfsutil hrename
ln -f hfsutil hrmdir
ln -f hfsutil humount
ln -f hfsutil hvol
cd librsrc && /Applications/Xcode.app/Contents/Developer/usr/bin/make
gcc -g -O2  -DHAVE_CONFIG_H   -c -o data.o data.c
gcc -g -O2  -DHAVE_CONFIG_H   -c -o rsrc.o rsrc.c
gcc -g -O2  -DHAVE_CONFIG_H   -c -o version.o version.c
ar rc librsrc.a data.o rsrc.o version.o
ranlib librsrc.a
cd libhfs && /Applications/Xcode.app/Contents/Developer/usr/bin/make
make[1]: Nothing to be done for `all'.
/usr/bin/install -c -m 755 hfsutil "/retro68-build/toolchain//bin/."
for file in hattrib hcd hcopy hdel hdir hformat hls hmkdir hmount hpwd hrename hrmdir humount hvol; do  \
		ln -f "/retro68-build/toolchain//bin/hfsutil" "/retro68-build/toolchain//bin/$file";  \
	done
rm -f "/retro68-build/toolchain//bin/hfsutil"
for file in hfsutils.1 hattrib.1 hcd.1 hcopy.1 hdel.1 hdir.1 hformat.1 hls.1 hmkdir.1 hmount.1 hpwd.1 hrename.1 hrmdir.1 humount.1 hvol.1; do  \
		/usr/bin/install -c -m 644 doc/man/$file  \
		"/retro68-build/toolchain//man/man1/`basename $file .1`.1";  \
	done
cd librsrc && /Applications/Xcode.app/Contents/Developer/usr/bin/make
make[1]: Nothing to be done for `all'.
cd libhfs && /Applications/Xcode.app/Contents/Developer/usr/bin/make install
/usr/bin/install -c -m 644 libhfs.a "/retro68-build/toolchain//lib/."
/usr/bin/install -c -m 644 hfs.h "/retro68-build/toolchain//include/."
cd librsrc && /Applications/Xcode.app/Contents/Developer/usr/bin/make install
/usr/bin/install -c -m 644 librsrc.a "/retro68-build/toolchain//lib/."
/usr/bin/install -c -m 644 rsrc.h "/retro68-build/toolchain//include/."
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   wave
--   filesystem
--   system
--   thread
--   regex
--   program_options
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   unit_test_framework
-- Configuring done
-- Generating done
-- Build files have been written to: /retro68-build/build-host
System is unknown to cmake, create:
Platform/Retro68 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
Your CMakeCache.txt file was copied to CopyOfCMakeCache.txt. Please send that file to cmake@www.cmake.org.
-- Configuring done
-- Generating done
-- Build files have been written to: /retro68-build/build-target
Scanning dependencies of target ResourceFiles
[  5%] Building CXX object ResourceFiles/CMakeFiles/ResourceFiles.dir/ResourceFile.cc.o
/Retro68/ResourceFiles/ResourceFile.cc:167:7: error: no member named 'cout' in namespace 'std'; did you mean 'count'?
        std::cout << "assigned: " << pathstring << " format " << (int)format << "\n";
        ~~~~~^~~~
             count
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:1083:1: note: 'count' declared here
count(_InputIterator __first, _InputIterator __last, const _Tp& __value_)
^
/Retro68/ResourceFiles/ResourceFile.cc:167:2: error: reference to overloaded function could not be resolved; did you mean to call it?
        std::cout << "assigned: " << pathstring << " format " << (int)format << "\n";
        ^~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:1083:1: note: possible target for call
count(_InputIterator __first, _InputIterator __last, const _Tp& __value_)
^
/Retro68/ResourceFiles/ResourceFile.cc:344:66: warning: implicit conversion from 'double' to 'size_type' (aka 'unsigned long') changes value from
      0.31 to 0 [-Wliteral-conversion]
                                hfsfile *file = hfs_create(vol, (path.stem().string().substr(0.31)).c_str(),
                                                                 ~~~~                        ^~~~
1 warning and 2 errors generated.
make[2]: *** [ResourceFiles/CMakeFiles/ResourceFiles.dir/ResourceFile.cc.o] Error 1
make[1]: *** [ResourceFiles/CMakeFiles/ResourceFiles.dir/all] Error 2
make: *** [all] Error 2
%
%
% brew list
boost	cmake	gmp	libmpc	mpfr	xz
% /Applications/Xcode.app/Contents/Developer/usr/bin/make —version
GNU Make 3.81
..
This program built for i386-apple-darwin11.3.0
% gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix
% ls ../Retro68/CIncludes/ | wc -l
     321

**Comment by CamHenlin** [comment]
I just wanted to chime in and say that I am having a similar issue but am not able to make it any further after installing boost, although it seems to print out that it sees boost 1.57.0 prior to stating Retro68/ResourceFiles/ResourceFile.cc:4:10: fatal error: 'boost/filesystem.hpp' file not found, is this maybe a different issue?

**Comment by autc04** [comment]
Should be fixed now. The boost dependency is also documented now.

@CamHenlin: If you have boost installed, that sounds like a different issue, can you post a log?

**Comment by CamHenlin** [comment]
Okay, I updated to the most recent version, same issue. Here's the last bit of my log, I can go back further if necessary:
...
make[1]: Nothing to be done for `all'.
cd libhfs && /Applications/Xcode.app/Contents/Developer/usr/bin/make install
/usr/bin/install -c -m 644 libhfs.a "/Users/camh/Documents/Retro68-build/toolchain//lib/."
/usr/bin/install -c -m 644 hfs.h "/Users/camh/Documents/Retro68-build/toolchain//include/."
cd librsrc && /Applications/Xcode.app/Contents/Developer/usr/bin/make install
/usr/bin/install -c -m 644 librsrc.a "/Users/camh/Documents/Retro68-build/toolchain//lib/."
/usr/bin/install -c -m 644 rsrc.h "/Users/camh/Documents/Retro68-build/toolchain//include/."
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   wave
--   filesystem
--   system
--   thread
--   regex
--   program_options
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   unit_test_framework
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/camh/Documents/Retro68-build/build-host
System is unknown to cmake, create:
Platform/Retro68 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
Your CMakeCache.txt file was copied to CopyOfCMakeCache.txt. Please send that file to cmake@www.cmake.org.
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/camh/Documents/Retro68-build/build-target
Scanning dependencies of target ResourceFiles
[  5%] Building CXX object ResourceFiles/CMakeFiles/ResourceFiles.dir/ResourceFile.cc.o
/Users/camh/Documents/Retro68/ResourceFiles/ResourceFile.cc:4:10: fatal error: 
      'boost/filesystem.hpp' file not found
#include <boost/filesystem.hpp>
         ^
1 error generated.
make[2]: *** [ResourceFiles/CMakeFiles/ResourceFiles.dir/ResourceFile.cc.o] Error 1
make[1]: *** [ResourceFiles/CMakeFiles/ResourceFiles.dir/all] Error 2
make: *** [all] Error 2

**Comment by marcusnilsen** [comment]
@CamHenlin Try removing the project and check it out again after you install/reinstall all the new homebrew packages, it worked for me to get rid of those errors.

After checking out the project with the new updates, it went further! But now it complains about not finding Processes.h and Sound.h (and maybe others?) in Retro68/libretro/start.c:

Retro68/libretro/start.c:23:23: fatal error: Processes.h: No such file or directory
Retro68/libretro/start.c:23:19: fatal error: Sound.h: No such file or directory

**Comment by autc04** [comment]
@CamHenlin: Try runnning

    xcode-select --install

I vaguely remember experiencing strange things after upgrading to Yosemite before I ran this. Maybe old command line tools left over or something.


P.S.: does someone know how to split up a github issue into multiple issues while preserving existing comments? We're now dealing with the third distinct problem under the same issue number, which will make this very confusing for posterity.

**Comment by CamHenlin** [comment]
I'm all set now, so I'll stop derailing. Thank you!

**Comment by marcusnilsen** [comment]
41e327debc7ebb83abb9078e3218714519fa5708 (installing bison) and f363d6d0a7f2624e3980d107f4e42abbe1ecbeea fixed these issues for me, thanks!
