### ISSUE TITLE
time(NULL) is off by +24 hours (minus TZ offset)

### ISSUE THREAD

**Issue by gpetersson** [autc04/Retro68#141]
I have a Linux system that is also running a qemu VM with OS 9.2.1. Both have the exact same date, time and timezone (EDT / GMT-4) set, down to the second.

When I compare the value of `time(NULL)` run on both OSes at the same time, I get:

Linux: 1631984893 or 2021-09-18 17:08:12
OS9: 1632056892 or 2021-09-19 13:08:12

It appears that the time returned by my Carbon app (compiled with Retro68 of course, commit beb4c2c5), at least under OS9, is 20 hours too fast, even though the Date&Time Control Panel in OS9 itself agrees with Linux. I assume the difference would be exactly 24 hours if the timezones were GMT.

Can you confirm if this is a toolchain issue?

**Comment by autc04** [comment]
Ah, yes. I rounded the number of leap years between the Mac Epoch (1904) and the Unix Epoch (1970) in the wrong direction.
Fix coming up.

**Comment by autc04** [comment]
Commit c124cf98d9c85f59f544f560deb9923b2b720b79 should fix this.

**Comment by gpetersson** [comment]
@autc04 Better, but it's still off by the TZ offset. So in my case it is 4 hours slow... I think `GetDateTime()` must not be returning GMT seconds.

**Comment by gpetersson** [comment]
Also perhaps helpful if you didn't know: it looks like the gmtDelta member of the MachineLocation struct needs some bitwise operations to read correctly:

![](https://i.imgur.com/EtJKuZY.png)
(from Operating_System_Utils_1994.pdf)

**Comment by gpetersson** [comment]
For reference I was able to get the right value within my own program by just writing my own function:

```c
static unsigned long myTime(void) {
  unsigned long secs = 0;
  long gmtDelta = 0;
  MachineLocation loc = {0};
  const int epochDifferenceInYears = 1970 - 1904;
  const int epochDifferenceInDays =
      365 * epochDifferenceInYears
      + (epochDifferenceInYears + 3)/ 4; /* round up for leap years */

  /* this adds the TZ offset to the result so we must subtract it afterwards */
  GetDateTime(&secs);

  secs -= 86400 * epochDifferenceInDays;

  ReadLocation(&loc);

  gmtDelta = loc.u.gmtDelta & 0xFFFFFF;

  if(BitTst(&gmtDelta, 23)) /* test sign extend bit */
    gmtDelta |= 0xFF000000;

  return secs - gmtDelta;
}
```
