### ISSUE TITLE
Standalone Makefile-based Hello World project

### ISSUE THREAD

**Issue by autc04** [autc04/Retro68#16]
Nothing beats a simple hand-written Makefile for understanding how things work.

**Comment by clehner** [comment]
See also https://github.com/clehner/Browsy/blob/master/Makefile and https://github.com/clehner/c-streams/blob/master/Makefile ;)

**Comment by autc04** [comment]
The HelloWorld and Raytracer samples now come with simple handwritten Makefiles; their CMakeLists.txt can also be used for standalone building.
