### ISSUE TITLE
libretro license prevents building non-GPLv3 software

### ISSUE THREAD

**Issue by Midar** [autc04/Retro68#17]
So, the way I understand it, basically everything you build needs libretro. However, libretro seems to be licensed as GPLv3. This basically means that you are not allowed to use Retro68 to compile any software that is not released under the GPLv3.

Would it be possible to switch libretro to either LGPLv3 or add the compiler exception there like is done with libgcc?

**Comment by autc04** [comment]
Yes, I will add the GPL Runtime Exception.

Note that the current restrictions only apply to *distributing* binaries.
I hadn't expected this to become an issue - is there still a motive for creating new non-GPL-compatible code for a platform that's been dead for 20 years? I'm curious.

**Comment by Midar** [comment]
Well, there's no real desire on my side for distribution binaries, as my main interest in Retro68 is to port ObjFW to classic Mac just because it's cool :). However, I could imagine some SDL-based games being interested in shipping binaries?

**Comment by autc04** [comment]
I've now added the exception (commit 0561012bb63e386b76f4a5699cd857ee7259ea06) to the file headers in libretro.
