### ISSUE TITLE
How do I compile a OpenGL program with this for OS X?

### ISSUE THREAD

**Issue by EGAMatsu** [autc04/Retro68#200]
I am having some issues with compiling a FreeGlut program, are there any PPC freeglut lib files i can grab or something?

**Comment by autc04** [comment]
* This targets classic Mac OS. Mac OS X is only supported via CarbonLib.
* FreeGLUT was never ported to native classic macos
* standard GLUT was part of Apple's OpenGL SDK.
* I know of no reason why the OpenGL SDK should not be usable, but I haven't tried it, either, so expect trouble.

**Comment by IoIxD** [comment]
It is not. You cannot link to [the lib files that Apple provided](https://web.archive.org/web/20001118111300/http://developer.apple.com/opengl/downloads.html) as they're .lib files. That download provides the source, but it does not contain the implementation for any glut functions (glGetString, etc.). I think they're expected to be found in the OS itself, like InterfaceLib and etc. are, meaning that you have to support them within Retro68.

Please consider reopening this and supporting this, this would open up a lot of good use cases for this.

**Comment by IoIxD** [comment]
As later brought up in a discussion, you have to convert the OpenGL files that Apple provided into the format that Retro68 wants.

I did so here: https://github.com/IoIxD/os9libs

**Comment by autc04** [comment]
Great!

And I have just finished a `nix`-based setup for OpenGL:

https://github.com/autc04/RetroOpenGL

That contains nix-based build scripts for the converted opengl, for GLUT, and a sample program.
