### ISSUE TITLE
Add a preprocessor macro to detect Retro68

### ISSUE THREAD

**Issue by johnsonjh** [autc04/Retro68#209]
It would be nice to have `__RETRO68__` defined.  Or maybe`__Retro68__`? 

Perhaps, if built with Multiversal Interfaces, we could also define `__MULTIVERSAL__`, and with Universal Interfaces, we could define `__UNIVERSAL__` or something similar?

This will help greatly to make programs easily cross-platform.

Right now, the best thing I've found to detect Retro68 would be something like:

```c
#if defined(__GNUC__) && defined(pascal) && \
    ((defined(__embedded__) && defined(__m68k__)) || \
      (defined(__ppc__) && defined(__pixel)))
# define __RETRO68__ 1
#endif
```

This is hacky and brittle, so something official would be welcome.

Edit: Would it also make sense to also define something based on the target OS, like `_SYSTEM_6`, etc?

**Comment by agoode** [comment]
I attached a pull request, it looks like historical compilers used `macintosh` and/or `Macintosh`, so I suggest that.
