### ISSUE TITLE
Raytracer sample fails to build

### ISSUE THREAD

**Issue by Midar** [autc04/Retro68#21]
[ 93%] Building C object Samples/Raytracer/CMakeFiles/Raytracer.dir/raytracer.c.obj
In file included from /Users/js/Devel/Retro68/build/toolchain/powerpc-apple-macos/include/Carbon.h:21:0,
                 from /Users/js/Devel/Retro68/Samples/Raytracer/raytracer.c:27:
/Users/js/Devel/Retro68/build/toolchain/powerpc-apple-macos/include/CoreServices.h:175:18: fatal error: fenv.h: No such file or directory
compilation terminated.
make[2]: *** [Samples/Raytracer/CMakeFiles/Raytracer.dir/raytracer.c.obj] Error 1
make[1]: *** [Samples/Raytracer/CMakeFiles/Raytracer.dir/all] Error 2
make: *** [all] Error 2

**Comment by autc04** [comment]
Can you tell me what exact version of Apple's interfaces you are using?

**Comment by mdanh2002** [comment]
I got this issue as well, when using MPW 3.5 header files. When using MPW 3.1 header files there are other missing headers. I resorted to replacing the content of the Raytracer sample application with the HelloWorld application, edit CMakeLists to set Raytracer as the output file. With this, Retro68 compiled fine, albeit without the Raytracer sample.

**Comment by autc04** [comment]
The MPW 3.5 issue should be fixed by 45bf39e1f7bdd138254f801feb9afc5a0e43f3ff.
