### ISSUE TITLE
ld warning after updating to latest GCC 12 version

### ISSUE THREAD

**Issue by rhalkyard** [autc04/Retro68#224]
Thanks a lot for your work on updating Retro68 to use GCC 12! I just pulled the latest updates and my projects seem to all build fine (minus a few new warnings about my sloppy code :) ). But I've noticed that there's a new warning from ld:

```
/home/rhalkyard/Retro68-build/toolchain/lib/gcc/m68k-apple-macos/12.2.0/../../../../m68k-apple-macos/bin/ld.real: warning: software/tools/diags/Diags.code.bin.gdb has a LOAD segment with RWX permissions
```

Is this to be expected? The build still succeeds and all the output files look correct, so it's not a big deal to just ignore it, but I thought I'd make a note of it just in case.

**Comment by autc04** [comment]
I think the warning is harmless, and we should therefore try to get rid of it.

theory/explanation: the ELF files specify that some code or data can be 'read, written and executed' (rwx), and this is
* not done any more on modern systems, as it is a security risk
* an unavoidable fact of life on 68K macs.
