### ISSUE TITLE
GCC: build failure on Sonoma

### ISSUE THREAD

**Issue by MaddTheSane** [autc04/Retro68#236]
Changes to the libc++ library seem to break the version of GCC that Retro68 uses. Specifically, `cp/mapper-client.o` fails because "'__abi_tag__' attribute only applies to structs, variables, functions, and namespaces". Maybe the C++ standard specified by the makefile is too low?
[out.log](https://github.com/autc04/Retro68/files/14817858/out.log)

**Comment by autc04** [comment]
Should be fixed by PR #241.
