### ISSUE TITLE
Universal Interfaces shared libraries don't get converted on non-Mac platforms

### ISSUE THREAD

**Issue by rhalkyard** [autc04/Retro68#259]
When building Retro68 with Universal Interfaces on a non-Mac platform, it fails to convert the Universal Interfaces shared libraries in `Interfaces&Libraries/Libraries/SharedLibraries` as their resource forks are not preserved. This is not immediately obvious to the user, as even when building with `--universal`, the build script falls back to the pre-built Multiversal libraries in this case, which do not appear to be a complete set. Thus, some builds that expect the Universal Interfaces shared libraries will then fail on a missing-library error.

I worked around the issue by MacBinary encoding the contents of `Interfaces&Libraries/Libraries/SharedLibraries` before transferring them, and patching `interfaces-and-libraries.sh` as follows:

```diff
--- a/interfaces-and-libraries.sh
+++ b/interfaces-and-libraries.sh
@@ -23,7 +23,7 @@ function locateInterfaceThing()
     local varname=$1
     local name=$2
     printf "Searching for %-25s" "$name..."
-    local found=`find -L "$INTERFACES_DIR"/ -name ".*" -prune -o -name $name -print`
+    local found=`find -L "$INTERFACES_DIR"/ -name ".*" -prune -o \( -name $name -o -name $name.bin \) -print`
     if [ -n "$found" ]; then
         eval "$varname=\$found"
         echo ${found#$INTERFACES_DIR/}
```

So long as the `.bin` extension is present, Retro68's tools automatically detect the MacBinary-encoded file with an intact resource fork, and appear to do the Right Thing in this case. Neat!

**Comment by autc04** [comment]
You have a point there.
AppleDouble and Basilisk formats worked before out of the box, but the documentation didn't clearly say so.

I've integrated your suggested change (thanks!) and added a few lines to the readme.
