### ISSUE TITLE
Add support for spaces

### ISSUE THREAD

**Issue by programmingkidx** [autc04/Retro68#270]
Hi, I request that paths with spaces be supported. 

In the file Retro68/build-toolchain.bash I encountered a problem with the spaces in the path. The fix was to enclose a path in double quotes. This is on line 231. This is how it looks like now: 
> "$SRC/binutils/configure" --target=m68k-apple-macos --prefix=$PREFIX 

The next error I encountered appears to be a policy issue. It was this message: 
> configure: WARNING: you should use --build, --host, --target
> configure: WARNING: invalid host type: application/Retro68-build/toolchain/
> configure: error: path to source, /Users/user/Documents/Development/Projects/benchmark application/Retro68/binutils, contains spaces

If supporting spaces is not possible then could a note be added on the main page that lets us know having spaces in the path would not work?

**Comment by ryandesign** [comment]
Very few build systems for software on Unix operating systems support spaces or other special characters in paths. It can be difficult for individual projects like Retro68 to fix that when the bugs may be in the build systems they use, such as CMake in the case of Retro68 itself or autotools for the gcc and binutils projects it bundles. I'm pretty sure the developers of autotools consider this a "wontfix" issue. I'm not sure it's reasonable to expect Retro68 and the countless other projects that use autotools to advertise this situation. If you're someone who builds software on Unix systems, you kind of just have to know that you're not supposed to use paths containing spaces or special characters.

**Comment by programmingkidx** [comment]
I see.
