### ISSUE TITLE
Unrecognized option --mac-strip-macsbug

### ISSUE THREAD

**Issue by TaraHoleInIt** [autc04/Retro68#28]
It looks like most, or all of the toolchain compiled successfully but errors out when it gets to the HelloWorld sample.

> /Users/tara/Retro68-build/toolchain/lib/gcc/powerpc-apple-macos/6.3.0/../../../../powerpc-apple-macos/bin/ld: unrecognized option '--mac-strip-macsbug'

Host OS: MacOS X Sierra 10.12

**Comment by autc04** [comment]
My bad. I've been hacking on 68K-specific things, and I passed my brand-new 68K-specific options for PowerPC as well.

(Use `build-toolchain.bash --skip-thirdparty` to save time after pulling this fix.)
