### ISSUE TITLE
"Unsupported relocation against"

### ISSUE THREAD

**Issue by MBeijer** [autc04/Retro68#29]
I'm trying to port MilkyTracker to PPC Mac OS 9, and I stumbled upon following error. Not sure if there's something I can do myself to fix this.

> ==== Building ppui (release_ppc-macos) ====
> Graphics_16BIT.cpp
> /tmp/cc6fPysU.s: Assembler messages:
> /tmp/cc6fPysU.s:338: Error: unsupported relocation against r9
> /tmp/cc6fPysU.s:339: Error: unsupported relocation against r10
> /tmp/cc6fPysU.s:339: Error: unsupported relocation against r5
> /tmp/cc6fPysU.s:341: Error: unsupported relocation against r10
> /tmp/cc6fPysU.s:341: Error: unsupported relocation against r9
> /tmp/cc6fPysU.s:345: Error: unsupported relocation against r4
> /tmp/cc6fPysU.s:345: Error: unsupported relocation against r3
> /tmp/cc6fPysU.s:346: Error: unsupported relocation against r4
> /tmp/cc6fPysU.s:346: Error: unsupported relocation against r3
> /tmp/cc6fPysU.s:347: Error: unsupported relocation against r4
> /tmp/cc6fPysU.s:347: Error: unsupported relocation against r3
> /tmp/cc6fPysU.s:348: Error: unsupported relocation against r4
> /tmp/cc6fPysU.s:348: Error: unsupported relocation against r3
> /tmp/cc6fPysU.s:349: Error: unsupported relocation against r10
> /tmp/cc6fPysU.s:349: Error: unsupported relocation against r10
> /tmp/cc6fPysU.s:350: Error: unsupported relocation against r3
> /tmp/cc6fPysU.s:350: Error: unsupported relocation against r3
> /tmp/cc6fPysU.s:351: Error: unsupported relocation against r10
> /tmp/cc6fPysU.s:351: Error: unsupported relocation against r9
> /tmp/cc6fPysU.s:353: Error: unsupported relocation against r11
> /tmp/cc6fPysU.s:353: Error: unsupported relocation against r5
> /tmp/cc6fPysU.s:355: Error: unsupported relocation against r11
> /tmp/cc6fPysU.s:355: Error: unsupported relocation against r9
> /tmp/cc6fPysU.s:358: Error: unsupported relocation against r4
> /tmp/cc6fPysU.s:358: Error: unsupported relocation against r3
> /tmp/cc6fPysU.s:359: Error: unsupported relocation against r11
> /tmp/cc6fPysU.s:359: Error: unsupported relocation against r11
> /tmp/cc6fPysU.s:360: Error: unsupported relocation against r3
> /tmp/cc6fPysU.s:360: Error: unsupported relocation against r3
> /tmp/cc6fPysU.s:361: Error: unsupported relocation against r11
> /tmp/cc6fPysU.s:361: Error: unsupported relocation against r9
> ppui.make:358: recipe for target 'obj/ppc-macos/Release/ppui/Graphics_16BIT.o' failed
> make[1]: *** [obj/ppc-macos/Release/ppui/Graphics_16BIT.o] Error 1
> Makefile:44: recipe for target 'ppui' failed
> make: *** [ppui] Error 2

**Comment by autc04** [comment]
No idea at first glance - Can you point me to the source code so that I can try to reproduce this?

The first step in debugging this would be to run `gcc -S` to get the assembler output of the compiler and then look at line 1358 of that to figure out what's wrong.

Did you verify that the samples are still working?

**Comment by MBeijer** [comment]
Sorry for the delay, here's the assembly file:
http://www.marlonbeijer.com/downloads/Graphics_16BIT.s

**Comment by autc04** [comment]
Oh, there's inline assembly involved:

https://github.com/milkytracker/MilkyTracker/blob/master/src/ppui/fastfill.h

This header file (included in the source file you're attempting to compile) contains PowerPC-specific inline assembly code written for Mac OS X. Apple's assembler for Mac OS X uses subtly different syntax from the GNU assembler that RetroPPC uses.

Luckily, the header file contains a plain C version of the code as well, so with a little change to the `#ifdef`s, you should be all set.

The assembly code doesn't do any particularly complicated optimizations, so our more modern version of GCC has a good chance of generating equally good code - no assembly required.

**Comment by MBeijer** [comment]
Oh, thank you! It was so obvious that I totally overlooked this! You can
close this issue! :)
