### ISSUE TITLE
--mac-single is broken and causes Dialog sample to crash.

### ISSUE THREAD

**Issue by autc04** [autc04/Retro68#33]
I broke it, some time recently.
Removing it doesn't hurt, but I only put it there so I'd notice if I break things.

**Comment by SteveBagley** [comment]
I'm still seeing issues when compiling Dialog (separately from the initial build) when the resulting program is run on a real Mac Plus, if --mac-single is left in the CMakeLists.txt.

With the Dialog directory as in GitHub and executing cmake/make I get a file of about 4K (see www.eprg.org/Dialog.bin) that throws an Address Error (in the middle of SetHandleSize in ROM according to MacsBug) on my Mac Plus but runs fine on miniVMac, Basilisk (emulating an LC475) and a Powerbook G3. Compiling without --mac-single gives a ~7K file (see www.eprg.org/Dialog.20180417.bin) that works fine on everything…

**Comment by autc04** [comment]
This commit fixes this on my Mac SE.
To test this new commit, `git pull` and then `make clean && make` in `Retro68-build/build-target`.

BTW, this was an excellent bug report. I had to set up my own real Mac SE to debug this, and your work that went into the bug report made sure that I didn't need to worry about anything else. Thanks!
