### ISSUE TITLE
ConvertObj support for OpenTransport.o

### ISSUE THREAD

**Issue by autc04** [autc04/Retro68#35]
currently fails with `flags == 0x10` assertion error.

**Comment by autc04** [comment]
Apparently needs support for 32-bit relocations (not hard),
and uses D0 for pointer returns.

gcc currently uses the "pointers in A0" convention followed by Metrowerks on the 68K, but apparently MPW returned pointers in D0. As we never link with metrowerks code, maybe we should just switch.
Implementing the pragma used in the OpenTransport headers to switch to MPW-compatible just for those functions is probably a lot harder.

**Comment by autc04** [comment]
ConvertObj can now deal with OpenTransport.o and the other OpenTransport object files.

However, the calling conventions don't match yet, calling an OpenTransport function that returns a pointer will crash (or, to be exact, yield an invalid pointer, which will lead to a crash)

**Comment by antscode** [comment]
I'm able to Convert the OpenTransport libs using ConvertObj, however when linking I get a number of undefined reference errors.

Most of the errors seem to relate to missing Globals - is there a chance that these are removed by ConvertObj? I'm able to correct these errors by defining the globals myself:

int errno;
int t_errno;
long __SLM11VTableDispatch;
long __SLM11ExtblDispatch;
long __SLM11ConstructorDispatch;
long __SLM11DestructorDispatch;

However I'm stuck on the this error: **undefined reference to `operator delete(void *)'**

The Internet says that this is fixed by including **stdc++** when linking, but I just can't get it to work.

My CMakeLists.txt looks like this:

add_application(my_app my_app.c CONSOLE)

target_link_libraries(my_app 
	stdc++
	OpenTransport.s 
	OpenTransportApp.s
	OpenTptInet.s)

Any assistance would be appreciated.

**Comment by autc04** [comment]
I didn't have the time to look into this more closely yet. A few first thoughts:

"The Internet says that this is fixed by including stdc++ when linking" - that's probably it, but I fear OpenTransport.o might need MPW's equivalent of `libstdc++`.

`errno` is obviously supposed to come from the C standard library, which is a (small) problem, too: The C library that Retro68 uses (newlib) doesn't have a real `errno` variable, but rather a fake one simulated using an `__errno()` function - for reasons of thread safety.

as for the `__SLM11*` symbols, they also look like they might be more than just `long` variables.


Can you send me/attach your test program so I have an easier time reproducing this?

**Comment by autc04** [comment]
First result: This is related to OpenTransport's use of the Apple Shared Library Manager, a technology for creating shared libraries that predates CFM and that was not used much outside of OpenTransport.

No idea yet what this means for us.

**Comment by antscode** [comment]
Thanks for your replies. I can prepare a simple test program this week - however today I was able to get MacTCP functioning via a Retro68 console app (over HTTP - yet to try TLS).

From my testing it also appears that MacTCP apps continue to function even when Open Transport is in use by the OS.

With that in mind, is your gut feel that getting Open Transport to work is going to be a complex job? In which case I'm happy to persist with MacTCP (although I don't know much about its limitations compared to Open Transport).

**Comment by autc04** [comment]
Stick with MacTCP for now.

Right now I cannot guess whether it will be easy (a little hack for `errno` plus the right `.o` files from Apple) or very hard.

With MacTCP, you might be able to run on older machines.
OpenTransport implements the old MacTCP APIs in addition to the new interfaces.

According to a file called ["Open Transport Technical Information"](http://www.wedophones.com/Manuals/AppleComputer/Open%20Transport%202-0%20Technical%20Information.pdf) (see page 10), this limits performance (mostly on PowerPC systems) and deprives you of the flexibility to run your program over something other than TCP instead.

So I'll try to figure out how hard this is and *then* decide whether it's fun enough to do.

**Comment by autc04** [comment]
... and finally, it works.

The Apple Shared Library Manager turned out to be not a problem after all, but there were several small bugs and omissions left in ConvertOBJ that made things fail in many different ways.
