### ISSUE TITLE
Build failed on object PEFTools/CMakeFiles/MakeImport.dir/MakeImport.cc.o

### ISSUE THREAD

**Issue by ZetZA** [autc04/Retro68#37]
I have been stuck on this compilation problem for a while:
[Compile output.txt](https://github.com/autc04/Retro68/files/1469908/Compile.output.txt)

Am I just doing something wrong, or did I just forget to include some headers?
I am compiling on a OS X High Sierra.

Thanks a lot!

**Comment by autc04** [comment]
The undeclared identifiers `PEFContainerHeader` and friends are supposed to come from `PEFBinaryFormat.h`, which should be copied from the universal interfaces you supply to `toolchain/include/` by the `build-toolchain.bash` script.

So, maybe you have an incompatible version of the headers - what version of Apple's interfaces are you using? What `PEFBinaryFormat.h` file is found in your `InterfacesAndLibraries` directory?

Note also that if you are interested in 68K development and not PowerPC, you can skip the whole problem by using `build-toolchain.bash --no-ppc`.

**Comment by ZetZA** [comment]
I am using the headers made available on macintoshgarden (http://macintoshgarden.org/sites/macintoshgarden.org/files/apps/InterfacesAndLibraries.zip). According to the description, these headers are from the Golden Master release, so I thought they should be fine. I'll try to download the complete GM version, and extract the headers directly, to see if that makes a difference.

I am actually only interested in 68K development, and tried compiling using the command `../Retro68/build-toolchain.bash --no-ppc`, but this causes the error for me.

**Comment by autc04** [comment]
I'll see if I can reproduce this in the evening.

The headers package seems fine.
Can you verify if the file `PEFBinaryFormat.h` is properly copied to the `toolchain/include` directory and has reasonable contents?

**Comment by ZetZA** [comment]
It is copied, but the file is empty

**Comment by autc04** [comment]
And there we have the problem... I'll have another look at this in the evening or tomorrow.

In the meantime, you can probably get the 68K part to compile by going to the top-level `CMakeLists.txt` and commenting out (`#`) the line

````
add_subdirectory(PEFTools)
````

**Comment by ZetZA** [comment]
Perfect, thank you very much for the support!

**Comment by autc04** [comment]
I cannot reproduce this on my Macbook Pro with High Sierra.

For the record, Retro68K should build on High Sierra out of the box, assuming the appropriate prerequisites have been installed from the homebrew package manager.

Is the `PEFBinaryFormat.h` problem reproducible?

Try this:
````
 ../Retro68/build-toolchain.bash --skip-thirdparty --no-ppc
````

(which should not take much time) and test whether toolchain/include/PEFBinaryFormat.h is copied properly this time.


For unrelated problems with building, feel free to open another issue.

**Comment by ZetZA** [comment]
I have now uninstalled and reinstalled all the brew packages as described in the README. I recloned the repository, and built it using the command that you recommended, but unfortunately with exactly the same result. I guess I must still be doing something wrong on my side, but oh well. I'll just have to make another plan.

Thanks a lot for taking the time to help.

**Comment by autc04** [comment]
Is there anything else you can tell me?

What are the "other errors" that you get when you tried to continue building?
Could you try copying PEFBinaryFormat.h over manually?

**Comment by ZetZA** [comment]
Okay so I have gone so far as to reinstall my OS, and I did get past the previous issue, but now, when I get to the "Install the project" part, I get the following output:

Install the project...
-- Install configuration: "Debug"
-- Installing: /.../Retro68-build/toolchain/bin/ResInfo
-- Installing: /.../Retro68-build/toolchain/bin/MakeAPPL
-- Installing: /.../Retro68-build/toolchain/bin/Rez
-- Installing: /.../Retro68-build/toolchain/bin/ConvertObj
-- Installing: /.../Retro68-build/toolchain/bin/Elf2Mac
-- Installing: /.../Retro68-build/toolchain/bin/LaunchAPPL
Preparing CIncludes...
sed: RE error: illegal byte sequence
sed: RE error: illegal byte sequence
sed: RE error: illegal byte sequence
...
sed: RE error: illegal byte sequence
Preparing RIncludes...
tr: Illegal byte sequence
tr: Illegal byte sequence
tr: Illegal byte sequence
tr: Illegal byte sequence
tr: Illegal byte sequence
tr: Illegal byte sequence

I feel like I'm really close to getting this installed 😅

**Comment by autc04** [comment]
This is interesting.
The `tr` and `sed` unix commands, which the install scripts use to process Apple's interface files (`tr` for chaning line endings from classic Mac style to unix, sed for searching and replacing things), seem to object to the original files' MacRoman character encoding (as opposed to modern UTF-8) for weird characters like ©.

Now, the thing is, this problem occured before, and I fixed it for my machine by setting some environment variables in the script to tell those commands not to insist on UTF-8.
For some reason, this fix is not working for your machine.

You can try this out on the command line. From the `CIncludes` directory inside `InterfacesAndLibrary`, try these commands one by one:

````
tr '\r' '\n' < PEFBinaryFormat.h > /dev/null
LANG=en tr '\r' '\n' < PEFBinaryFormat.h > /dev/null
LC_CTYPE=C tr '\r' '\n' < PEFBinaryFormat.h > /dev/null
````

They should either do nothing visible, or print an error message.
The middle version is the one the scripts are currently using, only the first version causes an error for me.

You could also run the command
````
env
````
and tell me all lines starting with `LANG=` or `LC_`. My own Mac has `LC_CTYPE=UTF-8` and no `LANG=` or other `LC_` entries.
