### ISSUE TITLE
-m68040 compiler option leads to crashes

### ISSUE THREAD

**Issue by autc04** [autc04/Retro68#38]
I've heard that https://github.com/antscode/MacHTTP crashes when `-m68040` is added to the compiler flags.

**Comment by autc04** [comment]
(reported by @antscode)

**Comment by cy384** [comment]
for the record, I've been messing around with my code, and I'm 90% confident this issue is caused by the 68k assembly used in mbed-tls, maybe also with some interaction with compiler optimization level

**Comment by cy384** [comment]
so I spent the night digging into this a little, compiling all my libraries and my main binary with "-march=68020 -O2", since without optimizations my program is not usable on 68k machines

I'm using mbedtls and libssh2, which are both designed to be very portable, and use a somewhat complicated system of macros and function pointers to wrap free and malloc

replacing all of the 'obfuscated' calls with actual simple free/malloc calls seems to fix all the crashes

**Comment by autc04** [comment]
Cool!

I've never really used those libs myself, can you provide some hints on what the minimal setup is to reproduce the problem? I've never really debugged this properly because setting up the whole thing didn't feel like it was my idea of fun :-)

**Comment by cy384** [comment]
sure, I'll write up a minimal program that can call mbedtls and crash, and some build instructions

**Comment by cy384** [comment]
so I haven't managed to get a simple reproduction without building my whole app with multiple libraries, but I've found some things:

* mbedtls has a config option where it only uses stack memory and does no mallocs/frees, and enabling that results in all mbedtls code working without errors (not surprising I guess)

* further into my program, libssh2 gives errors that malloc is returning null pointers (and mbedtls doesn't seem to check for null pointers as much, so maybe that was also a problem)

* increasing the memory in the get info box doesn't change anything

**Comment by autc04** [comment]
OK memAZErr sounds like heap corruption... Apparenty, if a bus error happens in the Memory Manager during some operations, that is caught and reported as an error instead of just crashing.
At least that's what I got from https://www.fenestrated.net/mac/mirrors/Apple%20Technotes%20(As%20of%202002)/me/me_14.html - that points to other reasons for the problem there, but those are all about bad 80's mac-specific practices, so I'm *pretty* sure that libssh/mbedtls don't do that.


It does look like I'll have the time to play around with this in the next few days, maybe I'll be able to rep

**Comment by autc04** [comment]
I now managed to set everything up, compiled everything for 68000 and only mbedtls for 020, and got a crash when I type `exit`.

It looks like it is indeed a compiler problem, looks like some references to the standard libraries are resolved incorrectly for 68020 code, causing a call to `free` to end up in the wrong place. But I'll need to investigate some more...

**Comment by autc04** [comment]
I just enjoyed a crash-free ssheven session now :-)
I still need to clean up a bit and maybe fix some collateral damage, so my fix is in a branch for now, the `r_68k_pc32` branch. Please give it a spin.  
(To test quickly, run `make install` in both the `build-target` and `build-host` directories, then rebuild ssheven)

For the record:
The problem was that the R_68K_PC32 relocation, i.e. support for instructions with 32-bit PC-relative offsets, was missing. If one of these instructions was used for a function call between different `CODE` segments, the jump ended up in the wrong place.

The instruction in question is the `BRA.L` instruction, which is quite rare as it is only used when tail call optimization applies, so things seemed to mostly work until a function named `aes_ctx_free` made a tail call to the standard library `free` function (which is in a different code segment).

**Comment by cy384** [comment]
fantastic, it's working great for me

this is so helpful, thanks a ton!
