### ISSUE TITLE
Missing types and functions

### ISSUE THREAD

**Issue by bparker06** [autc04/Retro68#39]
Working on porting an existing codebase to OS9, just compiled the toolchain from latest git and I'm seeing several missing things such as:

`/opt/retro68/powerpc-apple-macos/include/setjmp.h:15:6: error: unknown type name ‘jmp_buf’`

I'm guessing this one is due to _JBLEN not being set because `__PPC__` seems undefined:

```
$ powerpc-apple-macos-gcc -E -dM - </dev/null | grep PPC
#define _ARCH_PPC 1
```

Also:
`/opt/retro68/powerpc-apple-macos/include/stdlib.h:74:9: error: unknown type name ‘size_t’; did you mean ‘_ssize_t’?`
` warning: implicit declaration of function ‘setjmp’; did you mean ‘setbuf’? [-Wimplicit-function-declaration]`
`warning: implicit declaration of function ‘longjmp’; did you mean ‘log1p’? [-Wimplicit-function-declaration]`
`warning: implicit declaration of function ‘nanosleep’`

Any ideas?

**Comment by autc04** [comment]
Indeed, I've only been predefining __ppc__ and __POWERPC__, and I probably should be defining a few more.
I'll push a commit that adds __PPC__ to the list soon, but if you don't want to wait for that (and for the build-toolchain.bash to finish again), you can try building your code with -D__PPC_ and see if that fixes things.

**Comment by autc04** [comment]
Commit d7976cae6bf014045c004e60a1c7ac67262a0f07 makes powerpc-apple-macos-gcc predefine `__PPC__`. This should fix this particular problem.
