### ISSUE TITLE
Some traditional Mac glue code is missing from libretro

### ISSUE THREAD

**Issue by autc04** [autc04/Retro68#4]
Some functions are implemented in proprietary static libraries (without source code) in traditional Mac programming environments, and need to be duplicated for Retro68K.

This will lead to errors like

```
undefined reference to `FSClose'
```

The File Manager is probably most severly affected; the `PB*` and `PBH` calls are the real interface, whereas the `FS*` and `H*` calls are thin wrappers around them.

**Comment by autc04** [comment]
Retro68 now converts and uses MPW's `Interface.o` file, so this should now be solved.

**Comment by DarwinNE** [comment]
Hello,
  I try to compile an application that calls `SetFInfo`, but I get a "undefined reference to `SETFINFO'" error. `GetFInfo` seem to work correctly.

 I looked at https://github.com/autc04/Retro68/blob/e5185d23c3f690efa5d9e2be72abc09b01e48cd8/libretro/glue.c

and I found the code for `GetFInfo`, but not for `SetFInfo`. Is indeed missing or I am looking at the wrong spot and I forgot a compile option?

Kind regards,
D.

**Comment by autc04** [comment]
Indeed missing - this is now https://github.com/autc04/multiversal/issues/1.
I am assuming you are using the open-source "multiversal" interfaces instead of Apple's Universal Interfaces.
Incidentally, I should delete `libretro/glue.c`, its contents moved to the multiversal repo and it is not being used any more.

**Comment by DarwinNE** [comment]
I haven't installed the Apple's Universal Interfaces, so I guess I am using "multiversal".
