### ISSUE TITLE
Elf2Mac crash with cpp files and --mac-flat

### ISSUE THREAD

**Issue by antscode** [autc04/Retro68#49]
I've created a sample Control Panel (cdev) with an INIT resource - see attached source.

If I attempt to include a C++ file via add_executable, I get a crash during compilation:

    ...
    [ 85%] Linking CXX executable ControlPanel.flt
    collect2 : fatal error : ld terminated with signal 6 [Aborted], core dumped
    compilation terminated.
    Invalid ref from .data:13bc to .text(std::exception::~exception())+196516
    needsJT: false
    from addr: 196516, exceptionInfoStart: 0
    assertion "sym.section.get() == this" failed: file "/home/AnthonySuper/Retro68/Elf2Mac/Section.cc", line 205, function: void Section::FixRelocs()

Is this fixable, or is is not possible to include C++ files in a flat data file?

[ControlPanel.zip](https://github.com/autc04/Retro68/files/1746277/ControlPanel.zip)

**Comment by autc04** [comment]
Now fixed by commit 1bf9012d5ec7bff6a26bb15bc3643913e097b993.

(`make && make install` in the `Retro68-build/build-host/Elf2Mac` subdirectory should be enough.)

**Comment by antscode** [comment]
Thank you, thank you, thank you. The fix worked perfectly and I'm back in action.

Cheers!
