### ISSUE TITLE
PowerPC fails to compile

### ISSUE THREAD

**Issue by MaddTheSane** [autc04/Retro68#57]
When building GCC for PowerPC, it errors out:

    Retro68/gcc/gcc/function.c:5516:11: error: use of undeclared identifier 'IS_PASCAL_FUNC'
          if (IS_PASCAL_FUNC(TREE_TYPE(current_function_decl), current_function_decl))
              ^

I was able to track it down to commit 9d304134f2f437234900739e2aeda7a6ba58e873

**Comment by autc04** [comment]
Thanks... that was a dumb oversight. It should be fixed now.
