### ISSUE TITLE
LaunchAPPL "Not a bootable Mac disk image" error when using Mini vMac

### ISSUE THREAD

**Issue by Justin-Credible** [autc04/Retro68#76]
When attempting to use `LaunchAPPL` to start Mini vMac, I'm receiving the following error:

```
$ LaunchAPPL ./build/MyApp.APPL
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Not a bootable Mac disk image: /...path.../System_Startup_6.0.8.dsk
Abort trap: 6
```

I've verified the disk image works with Mini vMac directly by starting the emulator manually and then dragging and dropping my ROM and the above disk image onto the window. The emulator successfully boots to the System 6 Finder. It's just `LaunchAPPL` that is not happy with the disk image.

Here are the MD5 hashes of the ROM and disk image I am using:
ROM: `8a41e0754ffd1bb00d8183875c55164c`
Disk Image: `fe9edabb078a73b6d3f11c35425a7fc5`

I obtained the disk image from the Mini vMac page [here](https://www.gryphel.com/c/minivmac/start.html).

I can see that [these two lines](https://github.com/autc04/Retro68/blob/master/LaunchAPPL/Client/MiniVMac.cc#L88-L89) contain the check that my image is failing. I'm not sure if this check is too strict, or I'm using entirely the wrong disk image. I didn't see anything in the documentation that says what type of image I should be using.

Can you offer any suggestions?

**Comment by autc04** [comment]
LaunchAPPL currently only works with "raw" disk images, i.e. files that contain exactly the data the disk would contain, and nothing else.

Looks like the disk image on the vMac page is in an old DiskCopy format which LaunchAPPL isn't yet equipped to handle. The format is undocumented, but it seems simple enough, there's just an extra 84 byte header tacked on to the beginning. Apparently, Mini vMac has code to recognize and skip this header.

Disk Utility on current macOS allows me to convert the image to a regular "read/write" disk image, which is the format that LaunchAPPL uses.

Patches to make LaunchAPPL recognize and convert this image format are welcome, though I might get around to it myself eventually.

**Comment by Justin-Credible** [comment]
Ah! I didn't realize I was using a DiskCopy image. I converted it to raw image and now everything is working as expected.

I ended up using [this](https://www.bigmessowires.com/dc2dsk.c) to do the conversion. It may help you if you decide to DiskCopy support directly to `LaunchAPPL`.

Thanks again!
