### ISSUE TITLE
Compilation fails at building StreamBasedLauncher

### ISSUE THREAD

**Issue by ZetZA** [autc04/Retro68#80]
I am having the following problem while compiling the project. 

```
[ 97%] Building CXX object LaunchAPPL/Client/CMakeFiles/LaunchAPPL.dir/SSH.cc.o
[ 98%] Building CXX object LaunchAPPL/Client/CMakeFiles/LaunchAPPL.dir/StreamBasedLauncher.cc.o
/Retro68/LaunchAPPL/Client/StreamBasedLauncher.cc: In member function ‘virtual bool StreamBasedLauncher::Go(int)’:
/Retro68/LaunchAPPL/Client/StreamBasedLauncher.cc:55:28: error: aggregate ‘std::ostringstream rsrcOut’ has incomplete type and cannot be defined
         std::ostringstream rsrcOut;
                            ^~~~~~~
make[2]: *** [LaunchAPPL/Client/CMakeFiles/LaunchAPPL.dir/build.make:167: LaunchAPPL/Client/CMakeFiles/LaunchAPPL.dir/StreamBasedLauncher.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:714: LaunchAPPL/Client/CMakeFiles/LaunchAPPL.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

I have tried on numerous machines, and have checked that I installed the listed dependencies, however the compilation seems to always fail at exactly the same step. Any suggestions on what I might be doing wrong?

I have tried on Ubuntu, Arch Linux and Manjaro.

**Comment by autc04** [comment]
Looks like a `#include <sstream>` is missing at the top of that file.

(The C++ standard says it's required, but sometimes compilers let one get away without it in certain situations)

**Comment by ZetZA** [comment]
Thanks for the quick response. 

After adding the header, the compilation does go further, only to crash at:

```
Scanning dependencies of target ConsoleTest_APPL
[ 13%] Generating ConsoleTest.bin, ConsoleTest.APPL, ConsoleTest.dsk, ConsoleTest.ad, %ConsoleTest.ad
Rez: /Retro68-build/build-host/Rez/RezParser.generated.hh:364: T& yy::variant<S>::as() [with T = int; long unsigned int S = 48]: Assertion `yytypeid_' failed.
make[2]: *** [Console/CMakeFiles/ConsoleTest_APPL.dir/build.make:61: Console/ConsoleTest.bin] Aborted (core dumped)
make[1]: *** [CMakeFiles/Makefile2:187: Console/CMakeFiles/ConsoleTest_APPL.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

Is this a similar problem?

I also noticed, that before it gets to this point, it logs the following message a bunch of times for different files:

```
Creating Symlinks for CIncludes and RIncludes...
Converting 68K static libraries...
              AEObjectSupportLib.o => libAEObjectSupportLib.a       
                     ddrt881.far.o => libddrt881.far.a              
                         ddrt881.o => libddrt881.a                  
Unsupported relocation flags: 0x90
MPW .o files with near-model global variables or calls to imported functions will not work.
Cannot convert this file.
```
Is this normal?

Thanks again for the help :)

**Comment by autc04** [comment]
The "cannot convert" lines are normal, Retro68 just can't convert/use the "near" versions of those MPW libraries yet.

The other thing - what version of `bison` do you have installed?

**Comment by ZetZA** [comment]
I have version 3.2 installed

**Comment by autc04** [comment]
Oh... turns out this is exactly issue #72. Please upgrade to bison 3.2.4 (or later, 3.3.* is fine as well).

**Comment by ZetZA** [comment]
Yeah that was the problem. Thanks for the help! Issue can be closed
