### ISSUE TITLE
make: *** [all] Error 2

### ISSUE THREAD

**Issue by vincpa** [autc04/Retro68#83]
When building this solution with all of the prerequsites installed and the Interfaces and Libraries, I get an error during build.

Build environment is Ubuntu Bash. 

A condensed version of the output, only showing the last few lines.

I'm quite happy to also help out here, I just some pointers so I know where to look

mv -f $depbase.Tpo $depbase.Po
depbase=`echo config/obj-elf.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I/mnt/c/Users/Vince/source/Retro68/binutils/gas  -I. -I/mnt/c/Users/Vince/source/Retro68/binutils/gas -I../bfd -I/mnt/c/Users/Vince/source/Retro68/binutils/gas/config -I/mnt/c/Users/Vince/source/Retro68/binutils/gas/../include -I/mnt/c/Users/Vince/source/Retro68/binutils/gas/.. -I/mnt/c/Users/Vince/source/Retro68/binutils/gas/../bfd -DLOCALEDIR="\"/mnt/c/Users/Vince/source/Retro68-build/toolchain/share/locale\"" -I/usr/local/include -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -Wwrite-strings -I/mnt/c/Users/Vince/source/Retro68/binutils/gas/../zlib -g -O2 -MT config/obj-elf.o -MD -MP -MF $depbase.Tpo -c -o config/obj-elf.o /mnt/c/Users/Vince/source/Retro68/binutils/gas/config/obj-elf.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo config/atof-ieee.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I/mnt/c/Users/Vince/source/Retro68/binutils/gas  -I. -I/mnt/c/Users/Vince/source/Retro68/binutils/gas -I../bfd -I/mnt/c/Users/Vince/source/Retro68/binutils/gas/config -I/mnt/c/Users/Vince/source/Retro68/binutils/gas/../include -I/mnt/c/Users/Vince/source/Retro68/binutils/gas/.. -I/mnt/c/Users/Vince/source/Retro68/binutils/gas/../bfd -DLOCALEDIR="\"/mnt/c/Users/Vince/source/Retro68-build/toolchain/share/locale\"" -I/usr/local/include -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -Wwrite-strings -I/mnt/c/Users/Vince/source/Retro68/binutils/gas/../zlib -g -O2 -MT config/atof-ieee.o -MD -MP -MF $depbase.Tpo -c -o config/atof-ieee.o /mnt/c/Users/Vince/source/Retro68/binutils/gas/config/atof-ieee.c &&\
mv -f $depbase.Tpo $depbase.Po
/bin/bash ./libtool  --tag=CC   --mode=link gcc -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -Wwrite-strings -I/mnt/c/Users/Vince/source/Retro68/binutils/gas/../zlib -g -O2  -static-libstdc++ -static-libgcc -L/usr/local/lib -o as-new app.o as.o atof-generic.o compress-debug.o cond.o depend.o dwarf2dbg.o dw2gencfi.o ecoff.o ehopt.o expr.o flonum-copy.o flonum-konst.o flonum-mult.o frags.o hash.o input-file.o input-scrub.o listing.o literal.o macro.o messages.o output-file.o read.o remap.o sb.o stabs.o subsegs.o symbols.o write.o config/tc-m68k.o config/obj-elf.o config/atof-ieee.o m68k-parse.o ../opcodes/libopcodes.la ../bfd/libbfd.la ../libiberty/libiberty.a   -ldl
libtool: link: gcc -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -Wwrite-strings -I/mnt/c/Users/Vince/source/Retro68/binutils/gas/../zlib -g -O2 -static-libstdc++ -static-libgcc -o as-new app.o as.o atof-generic.o compress-debug.o cond.o depend.o dwarf2dbg.o dw2gencfi.o ecoff.o ehopt.o expr.o flonum-copy.o flonum-konst.o flonum-mult.o frags.o hash.o input-file.o input-scrub.o listing.o literal.o macro.o messages.o output-file.o read.o remap.o sb.o stabs.o subsegs.o symbols.o write.o config/tc-m68k.o config/obj-elf.o config/atof-ieee.o m68k-parse.o  -L/usr/local/lib ../opcodes/.libs/libopcodes.a ../bfd/.libs/libbfd.a -L/mnt/c/Users/Vince/source/Retro68-build/binutils-build/zlib -lz ../libiberty/libiberty.a -ldl
make[4]: Leaving directory '/mnt/c/Users/Vince/source/Retro68-build/binutils-build/gas'
make[3]: Leaving directory '/mnt/c/Users/Vince/source/Retro68-build/binutils-build/gas'
make[2]: Leaving directory '/mnt/c/Users/Vince/source/Retro68-build/binutils-build/gas'
make[2]: Entering directory '/mnt/c/Users/Vince/source/Retro68-build/binutils-build/binutils'
if [ -r sysinfo.c ]; then \
  gcc -c -I. -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -I/mnt/c/Users/Vince/source/Retro68/binutils/binutils/../zlib -g -O2  sysinfo.c ; \
else \
  gcc -c -I. -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -I/mnt/c/Users/Vince/source/Retro68/binutils/binutils/../zlib -g -O2  /mnt/c/Users/Vince/source/Retro68/binutils/binutils/sysinfo.c ; \
fi
make[2]: Entering directory '/mnt/c/Users/Vince/source/Retro68-build/binutils-build/gprof'
/bin/bash /mnt/c/Users/Vince/source/Retro68/binutils/binutils/../ylwrap /mnt/c/Users/Vince/source/Retro68/binutils/binutils/syslex.l .c syslex.c -- /mnt/c/Users/Vince/source/Retro68/binutils/missing flex
make  all-recursive
Making info in doc
make[3]: Entering directory '/mnt/c/Users/Vince/source/Retro68-build/binutils-build/gprof'
make[3]: Entering directory '/mnt/c/Users/Vince/source/Retro68-build/binutils-build/binutils/doc'
if test -f cxxfilt.man; then \
  man=cxxfilt.man; \
else \
  man=/mnt/c/Users/Vince/source/Retro68/binutils/binutils/doc/cxxfilt.man; \
fi; \
sed -e 's/@PROGRAM@/c++filt/' \
    -e 's/cxxfilt/c++filt/' < $man \
        > c++filt.1
Making all in po
make[3]: Leaving directory '/mnt/c/Users/Vince/source/Retro68-build/binutils-build/binutils/doc'
Making info in po
make[4]: Entering directory '/mnt/c/Users/Vince/source/Retro68-build/binutils-build/gprof/po'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/mnt/c/Users/Vince/source/Retro68-build/binutils-build/gprof/po'
make[3]: Entering directory '/mnt/c/Users/Vince/source/Retro68-build/binutils-build/binutils/po'
make[3]: Nothing to be done for 'info'.
make[3]: Leaving directory '/mnt/c/Users/Vince/source/Retro68-build/binutils-build/binutils/po'
/mnt/c/Users/Vince/source/Retro68/binutils/missing: 81: /mnt/c/Users/Vince/source/Retro68/binutils/missing: flex: not found
make[3]: Entering directory '/mnt/c/Users/Vince/source/Retro68-build/binutils-build/binutils'
make[3]: Nothing to be done for 'info-am'.
make[3]: Leaving directory '/mnt/c/Users/Vince/source/Retro68-build/binutils-build/binutils'
make[4]: Entering directory '/mnt/c/Users/Vince/source/Retro68-build/binutils-build/gprof'
WARNING: 'flex' is missing on your system.
         You should only need it if you modified a '.l' file.
         You may want to install the Fast Lexical Analyzer package:
         <http://flex.sourceforge.net/>
Makefile:1079: recipe for target 'syslex.c' failed
make[2]: *** [syslex.c] Error 127
make[2]: *** Waiting for unfinished jobs....
/bin/bash ./libtool  --tag=CC   --mode=link gcc -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -g -O2  -static-libstdc++ -static-libgcc -L/usr/local/lib -o gprof basic_blocks.o call_graph.o cg_arcs.o cg_dfn.o cg_print.o corefile.o gmon_io.o gprof.o hertz.o hist.o source.o search_list.o symtab.o sym_ids.o utils.o i386.o alpha.o vax.o sparc.o mips.o aarch64.o flat_bl.o bsd_callg_bl.o fsf_callg_bl.o ../bfd/libbfd.la ../libiberty/libiberty.a  -lm -ldl
make[2]: Leaving directory '/mnt/c/Users/Vince/source/Retro68-build/binutils-build/binutils'
Makefile:3573: recipe for target 'all-binutils' failed
make[1]: *** [all-binutils] Error 2
make[1]: *** Waiting for unfinished jobs....
libtool: link: gcc -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -g -O2 -static-libstdc++ -static-libgcc -o gprof basic_blocks.o call_graph.o cg_arcs.o cg_dfn.o cg_print.o corefile.o gmon_io.o gprof.o hertz.o hist.o source.o search_list.o symtab.o sym_ids.o utils.o i386.o alpha.o vax.o sparc.o mips.o aarch64.o flat_bl.o bsd_callg_bl.o fsf_callg_bl.o  -L/usr/local/lib ../bfd/.libs/libbfd.a -L/mnt/c/Users/Vince/source/Retro68-build/binutils-build/zlib -lz ../libiberty/libiberty.a -lm -ldl
make[4]: Leaving directory '/mnt/c/Users/Vince/source/Retro68-build/binutils-build/gprof'
make[3]: Leaving directory '/mnt/c/Users/Vince/source/Retro68-build/binutils-build/gprof'
make[2]: Leaving directory '/mnt/c/Users/Vince/source/Retro68-build/binutils-build/gprof'
make[1]: Leaving directory '/mnt/c/Users/Vince/source/Retro68-build/binutils-build'
Makefile:848: recipe for target 'all' failed
make: *** [all] Error 2
vince@sp-win:/mnt/c/Users/Vince/source/Retro68-build$

**Comment by autc04** [comment]
Looks like you're building on a Windows "C" drive - Is this Ubuntu in WSL on Windows? I've never tried that before.

For some reason `make` seams to thing that `binutils/binutils/syslex.l` is newer than `binutils/binutils/syslex.c`, and tries to rebuild the latter. For that, you would need to install the `flex` tool (`apt install flex`).
But this should not be necessary, as `syslex.l` is most definitely not newer than `syslex.c`.

I assume that the behaviour of file modification times is different in subtle ways when building on a Windows volume.
You can try installing flex and hope that this was the only such problem, or you can try building in your Ubuntu home directory and hope the problem disappears. In the latter case, the main disadvantage is that you can't (easily?) access that directory from Windows apps.

**Comment by vincpa** [comment]
Thanks for your prompt response.

I'll try your solution with flex and let you know how I go.

**Comment by vincpa** [comment]
Worked great on Ubuntu.
