### ISSUE TITLE
Sample Makefile is outdated - How to build a simple app with Retro68 without using cmake?

### ISSUE THREAD

**Issue by DarwinNE** [autc04/Retro68#98]
Hello,
   I could successfully compile Retro68 on my computer (a MacBook running MacOSX 10.13.6).
I was able to successfully compile and run the provided Hello World example (located in Retro68-build/build-target/Samples/HelloWorld), where the build system is fairly complex and based on CMake.

I would like now to compile a simple hello.c file using a single makefile, without using CMake and I am experiencing some difficulties.

Here is my makefile:

~~~~
# path to RETRO68
RETRO68=path-to-Retro68-dir/Retro68-build/toolchain


PREFIX=$(RETRO68)/m68k-apple-macos
CC=$(RETRO68)/bin/m68k-apple-macos-gcc
CXX=$(RETRO68)/bin/m68k-apple-macos-g++
REZ=$(RETRO68)/bin/Rez

LDFLAGS=-lRetroConsole -lretrocrt
RINCLUDES=$(PREFIX)/RIncludes
REZFLAGS=-I$(RINCLUDES)

HelloWorld.bin HelloWorld.APPL HelloWorld.dsk: HelloWorld.flt
	$(REZ) $(REZFLAGS) \
		-DFLT_FILE_NAME="\"HelloWorld.flt\"" "$(RINCLUDES)/Retro68APPL.r" \
		-t "APPL" -c "????" \
		-o HelloWorld.bin --cc HelloWorld.APPL --cc HelloWorld.dsk

HelloWorld.flt: hello.o
	$(CXX) $< -o $@ $(LDFLAGS)	# C++ used for linking because RetroConsole needs it

.PHONY: clean
clean:
	rm -f HelloWorld.bin HelloWorld.APPL HelloWorld.dsk HelloWorld.flt HelloWorld.flt.gdb hello.o
~~~~

My hello.c is very simple:
~~~~
#include<stdio.h>

int main(int argc, char** argv)
{
    printf("Hello World.\n");
    getchar();
    return 0;
}
~~~~

My makefile (inspired by the one here: https://github.com/autc04/Retro68/tree/master/Samples/HelloWorld) produces several files:

~~~~
-rw-r--r--@ 1 davidebucci  staff       0  4 déc 14:33 HelloWorld.APPL
-rw-r--r--  1 davidebucci  staff     512  4 déc 14:33 HelloWorld.bin
-rw-r--r--  1 davidebucci  staff  819200  4 déc 14:33 HelloWorld.dsk
-rw-r--r--@ 1 davidebucci  staff       0  4 déc 14:33 HelloWorld.flt
-rwxr-xr-x  1 davidebucci  staff  180624  4 déc 14:33 HelloWorld.flt.gdb
-rw-r--r--@ 1 davidebucci  staff     813  4 déc 14:25 Makefile
-rw-r--r--  1 davidebucci  staff     114  4 déc 11:21 hello.c
-rw-r--r--  1 davidebucci  staff     816  4 déc 14:33 hello.o
~~~~

Unfortunately, if I try to use the HelloWorld.dsk in Basilisk II, it contains an executable that issue a 'The application program "HelloWorld" could not be opened, because an error of type -192 occourred'.

I had some difficulties understanding which libraries I do need for a simple console program; I guess RetroConsole must be included, but I am not sure about retrocrt.

If there is some documentation available about libraries and tools included in Retro68, where can I find it? I think I've understood that Rez is a very important tool, but how can I learn how to use it?

Thanks in advance,
D.

**Comment by autc04** [comment]
Oh... apparently, that sample Makefile is outdated. Stay tuned...

**Comment by autc04** [comment]
Okay, the sample Makefile is updated.

What changed? Basically, "flt" files aren't used anymore. Instead, the output of the compiler is already a mac application (which can be encoded as MacBinary by adding a .bin extension). The `Rez` command invocation has changed to copy that application (`--copy`) and add extra resources (for a simple HelloWorld, that's only the 'SIZE' resource that tells the Mac how much RAM your application needs, among other things, but you can add more here).

Ways to learn more about Rez:
* Apple's MPW manual has a chapter about the exact syntax. I saw a copy here: http://www.robertocipriani.it/MPW/mpw%20reference.pdf
* Read between the lines of the Inside Macintosh books (the 90s era series, not the original volumes I-VI) - they often have Rez language examples for important resource types.
* ... or just don't: Grab a copy of ResEdit and run it using your favorite emulator, edit your resources using a nice GUI and save them in a `.rsrc` file. In your `Makefile`, specify that `.rsrc` file as parameter for Rez's `--copy` option. Of course, this makes using version control like `git` a lot less convenient.

**Comment by DarwinNE** [comment]
Gee, that's great!

Thank you very much for all this very useful information.

**Comment by DarwinNE** [comment]
I could successfully compile the Hello World example.

Many thanks, again!
