### ISSUE TITLE
Extra newline added by fgets reading stdin

### ISSUE THREAD

**Issue by DarwinNE** [autc04/Retro68#99]
Hi,
  I am playing with console programs with Retro68.

I noticed something strange, if I compile and run the following program (with the makefile as per #98):
~~~~
#include<stdio.h>
#include<string.h>

int main(int argc, char** argv)
{
    char buffer[256];
    int p=0;
    char c;

    printf("Hello World.\n");
    printf("Let's check some keyboard input. Type * to exit. \n");
    do {
        printf("> ");
        fflush(stdout);
        fgets(buffer,sizeof(buffer), stdin);
    
        for(p=0;(c=buffer[p])!=0;++p) {
            printf("We have a [%c], whose code is %d\n",c,c);
            if(c=='*')
                return 0;
        }
    } while(1);
    
    return 0;
}
~~~~

There are two things that I find strange, if compared with what I obtain running the same program on a modern Unix terminal:
- I must add the  fflush(stdout); just after the "prompt" written by printf("> "); as if I don't put it, the "> " is written only after fgets is processed.
- Each time I type return, the cycle is executed twice, as there is a spurious "\n" that is added at the successive call at fgets.

Are they normal behaviors?

Cheers,
D.

**Comment by autc04** [comment]
The double newline was a rather obvious bug, which is now fixed.

As for the flushing, the Internet contradicts itself a bit on whether the C standard requires it, and anyway I haven't yet figured out how to implement it (the `newlib` C library theoretically should have the functionality, but it's not triggered here for some reason).

**Comment by DarwinNE** [comment]
Hi,
  thank you very much!
I tried and it works very well.
It's not a big deal for me to leave some fflush(stdout); the newline bug was much more annoying in my code.

**Comment by blanham** [comment]
> 
> 
> The double newline was a rather obvious bug, which is now fixed.
> 
> As for the flushing, the Internet contradicts itself a bit on whether the C standard requires it, and anyway I haven't yet figured out how to implement it (the `newlib` C library theoretically should have the functionality, but it's not triggered here for some reason).

musl and newlib require you to flush, while glibc doesn't IIRC.
